version: '3.1'
services:
  frontend:
    image: gabrock/open-notes-frontend
    ports:
      - "3000:3000"
    links:
      - "backend:api"
  backend:
    image: moisesocosta/open-notes-api
    ports:
      - "8000:8000"
    links:
      - "database:db"
    environment:
      DATABASE_HOST: db
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  db-data:
